from setuptools import setup, find_packages

setup(
    name="logos",
    version="0.1.0",
    description="Logos",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Eden",
    author_email="gene@eden.art",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0.post1",
        "pydantic>=2.5.2",
        "python-dotenv>=1.0.0",
        "fire>=0.3.0",
        "httpx>=0.24.1",
        "orjson>=3.9.0",
        "rich>=13.4.1",
        "python-dateutil>=2.8.2",
        "pymongo>=3.12.0",
        "elevenlabs>=0.2.27",
        "boto3>=1.34.9",
        "replicate>=0.22.0",
        "moviepy>=1.0.3",
        "eden_sdk @ git+https://github.com/edenartlab/eden-sdk-py.git",
        "transformers>=4.37.2",
        "pydub>=0.25.1",
    ],
    python_requires=">=3.8",
    extras_require={
        "dev": [
            "pre-commit>=3.5.0",
            "black>=23.11.0",
            "mypy>=1.7.0",
            "flake8>=6.1.0",
            "pytest>=7.4.3",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
